volumes:
  pgdata:

services:

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db

    env_file:
      - .env
    working_dir: /app

    ports:
      - '8000:8000'

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/api/health" ]
      interval: 1m
      timeout: 10s
      retries: 3

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
